### ISSUE TITLE
When I try to remove the chromecast add-on I get an error

### ISSUE THREAD

**Issue by chasingmaxwell** [mrstegeman/chromecast-adapter#6]
From the add-ons page, I clicked "x Remove" and nothing happened. So I checked out the logs and saw this:

```
2020-05-21 11:23:48.729 INFO   : Unloading ChromecastAdapter
2020-05-21 11:23:48.738 ERROR  : chromecast-adapter: /home/pi/mozilla-iot/gateway/node_modules/gateway-addon/lib/addon-manager-proxy.js:321
2020-05-21 11:23:48.739 ERROR  : chromecast-adapter:         adapter.unload().then(() => {
2020-05-21 11:23:48.746 ERROR  : chromecast-adapter:                         ^
2020-05-21 11:23:48.747 ERROR  : chromecast-adapter:
2020-05-21 11:23:48.748 ERROR  : chromecast-adapter: TypeError: Cannot read property 'then' of undefined
2020-05-21 11:23:48.750 ERROR  : chromecast-adapter:     at AddonManagerProxy.onMsg (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/lib/addon-manager-proxy.js:321:25)
2020-05-21 11:23:48.751 ERROR  : chromecast-adapter:     at PluginClient.onMsg (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/lib/plugin-client.js:48:25)
2020-05-21 11:23:48.753 ERROR  : chromecast-adapter:     at IpcSocket.onData (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/lib/ipc.js:94:10)
2020-05-21 11:23:48.754 ERROR  : chromecast-adapter:     at WebSocket.emit (events.js:198:13)
2020-05-21 11:23:48.755 ERROR  : chromecast-adapter:     at Receiver.receiverOnMessage (/home/pi/mozilla-iot/gateway/node_modules/ws/lib/websocket.js:801:20)
2020-05-21 11:23:48.756 ERROR  : chromecast-adapter:     at Receiver.emit (events.js:198:13)
2020-05-21 11:23:48.758 ERROR  : chromecast-adapter:     at Receiver.dataMessage (/home/pi/mozilla-iot/gateway/node_modules/ws/lib/receiver.js:436:14)
2020-05-21 11:23:48.759 ERROR  : chromecast-adapter:     at Receiver.getData (/home/pi/mozilla-iot/gateway/node_modules/ws/lib/receiver.js:366:17)
2020-05-21 11:23:48.760 ERROR  : chromecast-adapter:     at Receiver.startLoop (/home/pi/mozilla-iot/gateway/node_modules/ws/lib/receiver.js:142:22)
2020-05-21 11:23:48.761 ERROR  : chromecast-adapter:     at Receiver._write (/home/pi/mozilla-iot/gateway/node_modules/ws/lib/receiver.js:77:10)
2020-05-21 11:23:48.770 INFO   : Plugin: chromecast-adapter died, code = 1 restarting after 0
```

**Comment by mrstegeman** [comment]
What gateway version are you using?

**Comment by chasingmaxwell** [comment]
0.12.0

**Comment by mrstegeman** [comment]
Thanks for reporting! Should be fixed in the next version.

**Comment by chasingmaxwell** [comment]
Fast turnaround! Thanks!
