### ISSUE TITLE
update to 0.4.3 failed

### ISSUE THREAD

**Issue by arist0v** [mrstegeman/chromecast-adapter#7]
trying to update to 0.4.3 but it seem to failed log:

```
2020-05-21 13:29:03.636 INFO   : Fetching add-on https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/chromecast-adapter-0.4.3.tgz as /tmp/fACpdH/chromecast-adapter.tar.gz
2020-05-21 13:29:05.557 INFO   : Expanding add-on /tmp/fACpdH/chromecast-adapter.tar.gz
2020-05-21 13:29:06.442 INFO   : Unloading ChromecastAdapter
2020-05-21 13:29:06.454 ERROR  : chromecast-adapter: /home/pi/mozilla-iot/gateway/node_modules/gateway-addon/lib/addon-manager-proxy.js:321
2020-05-21 13:29:06.455 ERROR  : chromecast-adapter:         adapter.unload().then(() => {
2020-05-21 13:29:06.457 ERROR  : chromecast-adapter:                         ^
2020-05-21 13:29:06.458 ERROR  : chromecast-adapter: 
2020-05-21 13:29:06.459 ERROR  : chromecast-adapter: TypeError: Cannot read property 'then' of undefined
2020-05-21 13:29:06.460 ERROR  : chromecast-adapter:     at AddonManagerProxy.onMsg (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/lib/addon-manager-proxy.js:321:25)
2020-05-21 13:29:06.462 ERROR  : chromecast-adapter:     at PluginClient.onMsg (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/lib/plugin-client.js:48:25)
2020-05-21 13:29:06.464 ERROR  : chromecast-adapter:     at IpcSocket.onData (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/lib/ipc.js:94:10)
2020-05-21 13:29:06.465 ERROR  : chromecast-adapter:     at WebSocket.emit (events.js:198:13)
2020-05-21 13:29:06.475 ERROR  : chromecast-adapter:     at Receiver.receiverOnMessage (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/node_modules/ws/lib/websocket.js:801:20)
2020-05-21 13:29:06.477 ERROR  : chromecast-adapter:     at Receiver.emit (events.js:198:13)
2020-05-21 13:29:06.478 ERROR  : chromecast-adapter:     at Receiver.dataMessage (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/node_modules/ws/lib/receiver.js:436:14)
2020-05-21 13:29:06.479 ERROR  : chromecast-adapter:     at Receiver.getData (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/node_modules/ws/lib/receiver.js:366:17)
2020-05-21 13:29:06.481 ERROR  : chromecast-adapter:     at Receiver.startLoop (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/node_modules/ws/lib/receiver.js:142:22)
2020-05-21 13:29:06.482 ERROR  : chromecast-adapter:     at Receiver._write (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/node_modules/ws/lib/receiver.js:77:10)
2020-05-21 13:29:06.485 INFO   : Plugin: chromecast-adapter died, code = 1 restarting after 0
```

**Comment by mrstegeman** [comment]
This is the issue I just fixed in #6 (which was the reason for this update). Moving forward, you should not see it again.

**Comment by arist0v** [comment]
i try to update to 0.4.3 but it didn'T work i even have try to reboot the
device

**Comment by mrstegeman** [comment]
Try removing the add-on and then re-installing it.

**Comment by arist0v** [comment]
i tryied, but the delete button get highlighted but nothing happen, i have
try with addon enable and disabled

**Comment by arist0v** [comment]
not sure how, but i finally get to update my plugin

Le jeu. 21 mai 2020, à 14 h 17, Martin Verret <verret.martin@gmail.com> a
écrit :
